# Configuration for 06_import_items_and_revisions

# Teamcenter connection details
# These should be for the TARGET environment
TC_USER=infodba
TC_PASS=infodba
TC_GROUP=dba

# Input file configuration
# This should be the file produced by the TRANSFORMATION step
INPUT_DIR=../output/transformed
ITEM_REVISION_INPUT_FILE=item_revisions_transformed.csv

# Load options
# What to do if an item with the same ID already exists in the target?
# supported values: SKIP, OVERWRITE
IF_EXISTS=SKIP

# Log file configuration
LOG_DIR=../logs
LOG_FILE_NAME=06_load_items_run.log
# This file will be created to map old IDs to new UIDs for subsequent scripts
UID_MAP_FILE=item_rev_uid_map.log
